//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTraking
    {
        public int Id { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdWorker { get; set; }
        public Nullable<int> IdProduct { get; set; }
    
        public virtual ClientSet ClientSet { get; set; }
        public virtual ProductSet ProductSet { get; set; }
        public virtual WorkerSet WorkerSet { get; set; }
    }
}
